---
title: "Final Project"
---

### **Key dates**

-   Sunday 04/26 at 12:00pm: project proposal due to Canvas

-   Saturday 05/09 at **11:59pm**: rough draft for peer review due to Canvas

    -   Peer review guidelines [here](weeks/project/peer_review_guide.pdf)

-   Thursday 05/14 at **9:00am**: project presentations during exam period.

-   Thursday 05/14 through Monday 05/18: 1:1 conversations with Becky

-   Sunday 05/17 at 11:59pm: final draft due to Canvas (**no reflection needed**)

------------------------------------------------------------------------

### Brief description

An important skill that a working statistician or mathematician should have is the ability to independently investigate an advanced topic and then communicate the findings to a wider audience. This final project is designed as an opportunity for you to demonstrate semester-long cumulative knowledge of the theory of mathematical statistics, and to investigate the framework and application of a particular statistical method or procedure. As part of your investigation, you will apply the method to a particular data set to answer a research question of interest. **Note: the emphasis of this project is on learning a new statistical inference method, technique, or concept. This is not intended to be a data analysis-forward project.**

You will work individually to research a topic in mathematical statistics beyond the scope of what we’ve covered in class. You will share your results in the following ways, each providing different ways of helping you practice sharing statistical knowledge:

1.  Via a 5 - 6 page research paper,
2.  Via a presentation to a wider audience, and
3.  Via a 15-20 minute 1:1 conversation with Becky

This is an opportunity to investigate an area of interest that isn’t covered in class this semester. Alternatively, you may dive deeper into a topic that we only briefly covered in class this semester. Possible topics will be shared later in the semester. Aside from the dataset you choose, you should not use topics/material learned from other courses/research for your final project!

## Details

See this [PDF](weeks/project/311_project.pdf) for more details about the final project!

-   Here's an [example](weeks/project/project_example.pdf) of a previous student's final paper

### Presentation order

Remember, \~10 minute presentations:

1.  Riley F.
2.  Benjamin H.
3.  Sunny H.
4.  Skylar W.
5.  Riley H.
6.  Shingo K.
7.  Haru K.
8.  Sebastian P.
9.  Isaac T.
10. Maria D.
