---
title: "Schedule"
format: 
  html: 
    toc: false
---

A high-level overview of the semester's topics are presented here. Please select a week for a specific day's assignments and materials.

### [Week 01](weeks/week-01.qmd)

-   Welcome!
-   Prior and posterior distributions

### [Week 02](weeks/week-02.qmd)

-   Conjugate priors

-   Bayes estimators

### [Week 03](weeks/week-03.qmd)

-   Maximum likelihood estimation

### [Week 04](weeks/week-04.qmd)

-   Method of moments
-   Bias, variance, MSE

### [Week 05](weeks/week-05.qmd)

-   Fisher information
-   Cramer-Rao Lower Bound

### SPRING BREAK

### [Week 06](weeks/week-06.qmd)

-   $\chi^2$ and $t$ distributions
-   Joint distribution of sample mean and variance

### [Week 07](weeks/week-07.qmd)

-   Confidence intervals

### [Week 08](weeks/week-08.qmd)

-   Bootstrapping

### [Week 09](weeks/week-09.qmd)

-   Hypothesis testing

### [Week 10](weeks/week-10.qmd)

-   p-values
-   Likelihood ratio test

### [Week 11](weeks/week-11.qmd)

-   $t$-tests

### [Week 12](weeks/week-12.qmd)

-   Simple linear regression
