---
title: "Newton-Raphson"
editor_options: 
  chunk_output_type: console
---

## Poisson example

```{r message= F}
library(tidyverse)
set.seed(311)
# simulate data
theta_true <- 4
n <- 20
x <- rpois(n, theta_true)

flag <- TRUE
eps <- 0.00000001

# initial guess
theta_curr <- x[1]
theta_vec <- c(theta_curr)

while(flag){
  # evaluate derivative(s)
  score <- -n + sum(x)/theta_curr
  score_prime <- -sum(x)/theta_curr^2
  # update parameter
  theta_new <- theta_curr - score/score_prime
  
  # store parameter
  theta_vec <- c(theta_vec, theta_new)
  
  # set flag to FALSE if we have converged
  if(abs(theta_new - theta_curr) < eps){
    flag <- FALSE
  }
  # set "new" parameter to be the previous parameter
  theta_curr <- theta_new
}

theta_mle <- mean(x)
data.frame(theta_est = theta_vec) |>
  mutate(iteration = row_number()) |>
  ggplot(aes(x = iteration, y = theta_est)) +
  geom_point() +
  geom_hline(yintercept = theta_mle, linetype = "dashed")

```

## Muon decay example

```{r}
# muon decay example
set.seed(10)
# simulate data via inverse CDF
count <- 1
n <- 25
theta_true <- 0.5
x <- c()
while(count <= n){
  u <- runif(1)
  a <- theta_true / 4
  b <- 1/2
  c <- 1/2 - theta_true/4 - u
  root <- (-b + c(-1, 1) * sqrt(b^2 - 4 * a * c))/(2*a)
  x <- c(x, root[which(root > -1 & root < 1)])
  count <- count + 1
}

# visualize log likelihood to see where MLE is in relation to true theta
theta_grid <- seq(-0.99,0.99,length=500)
loglik <- sapply(theta_grid,function(t){
  sum(log(1 + t*x))
})
(mle <- theta_grid[which.max(loglik)])
data.frame(theta = theta_grid, log_like = loglik) |>
  ggplot(aes(x = theta, y = log_like)) +
  geom_line() +
  geom_vline(xintercept = mle, linetype = "dashed", col = "orange")

# initial guess: MoM
theta_mom <- 3 * mean(x)
theta_curr <- theta_mom
theta_vec <- c(theta_curr)

flag <- TRUE
eps <- 0.0000000001

while(flag){
  # evaluate derivative(s)
  score <- sum(x / (1 + theta_curr * x))
  score_prime <- -sum(x^2 / (1 + theta_curr * x)^2)
  # update parameter
  theta_new <- theta_curr - score/score_prime
  # enforce parameter bounds??
  theta_new <- max(min(theta_new, 0.999), -0.999)
  
  # store parameter
  theta_vec <- c(theta_vec, theta_new)
  
  # set flag to FALSE if we have converged
  if(abs(theta_new - theta_curr) < eps){
    flag <- FALSE
  }
  # set "new" parameter to be the previous parameter
  theta_curr <- theta_new
}


data.frame(theta_est = theta_vec) |>
  mutate(iteration = row_number()) |>
  ggplot(aes(x = iteration, y = theta_est)) +
  geom_point() +
  geom_hline(yintercept = mle, linetype = "dashed", col = "orange") +
  labs(caption = "Dashed line is observed MLE")

```
